---

# add the host names
- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: uninstall apache2 package
    apt:
      name: apache2
      state: absent

  - name: uninstall htop package
    apt:
      name: htop
      state: absent

  - name: uninstall php support package
    apt:
      name: libapache2-mod-php
      state: absent

