## semaphore book auotmation

---
- hosts : all
  become : yes
  become_user: ka
  become_method: sudo

  tasks:
    - name: Update apt
      apt: 
        update_cache: yes 
        cache_valid_time: 600



