## semaphore book auotmation

---
- hosts : all
  become_user: ka
  become_method: sudo

  tasks:

    - name: Update apt
      become : yes
      sudo: yes
      apt: 
        update_cache: yes 
        cache_valid_time: 600




