## semaphore book auotmation
---
- name: Update apt cache
  hosts: all
  become_user: ka
  become: yes


  tasks:

    - name: Ensure apt is up to date
      apt:
        update_cache: yes
        cache_valid_time: 600
        
  # vars:
  #   ansible_ssh_private_key_file: /etc/ssh/ssh_host_ed25519_key.pub

# ---
# - hosts : all
#   become_user: ka
#   become_method: sudo

#   tasks:
#     - name: Update apt
#       sudo: yes
#       apt: 
#         update_cache: yes 
#         cache_valid_time: 600




