## semaphore book auotmation

---
- hosts : all
  become : true
  become_method: sudo
  # become_user: ka
  tasks:
    - name : update apt packages
      apt:
        upgrade: yes
        update_cache: yes
        force_apt_get: yes


