## semaphore book auotmation

---
- hosts : all
  become : yes
  become_user: ka
  tasks:
    # - name : update apt packages
    #   apt:
    #     upgrade: yes
    #     update_cache: yes
    #     force_apt_get: yes

    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest
        force_apt_get: yes      


