---
- name: Configure Fail2ban on Ubuntu
  hosts: your_target_server
  become: yes
  tasks:
    - name: Install Fail2ban
      apt:
        name: fail2ban
        state: present

    - name: Copy Fail2ban configuration for Apache
      template:
        src: templates/jail.local.j2
        dest: /etc/fail2ban/jail.local
      notify:
        - restart fail2ban

    - name: Create the whitelist file
      copy:
        content: |
          [DEFAULT]
          ignoreip = 192.168.170.0/24 172.17.2.11 172.17.2.100
        dest: /etc/fail2ban/whitelist.conf

    - name: Add whitelist file to Fail2ban configuration
      lineinfile:
        path: /etc/fail2ban/jail.local
        line: 'ignoreip = 192.168.170.0/24 172.17.2.11 172.17.2.100'
        regexp: '^ignoreip ='
      notify:
        - restart fail2ban

  handlers:
    - name: restart fail2ban
      service:
        name: fail2ban
        state: restarted
