---

- hosts: all
  become: true
  tasks:

   - name: install multiple packages
     package:
       name: 
         - "{{ apache_package }}"
         - "{{php_package}}" 
       state: absent
       update_cache : yes
     

  

    

    
