---
- name: prompt for  Project/Foldername
  hosts: localhost
  vars_prompt: 
      - name : Project 
        prompt : name of the project/customer?
        private: no 


  # task:

  #   - name : create project working directory
  #     file :
  #       path : "{{directory}}\{{ Project }}\group_vars"
  #       state: directory
  #     delegate_to : 172.17.2.128 