---

# add the host names
- hosts: ubuntu
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: install apache2 package
    apt:
      name: apache2
      state: absent

  - name: install htop package
    apt:
      name: htop
      state: absent

  - name: install php support package
    apt:
      name: libapache2-mod-php
      state: absent

