---
- name: Setup Environment
  hosts: 192.168.10.37
  remote_user: ka
  become: yes
  tasks:
    - name: Install Python 3
      raw: test -e /usr/bin/python3 || (dnf install -y python3 && alternatives --set python /usr/bin/python3)
      changed_when: false

    - name: Install dnf
      package:
        name: dnf
        state: present

- name: Update Hosts File
  hosts: 192.168.10.37
  remote_user: ka
  become: yes
  tasks:
    - name: Add host entries to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items:
        - "192.168.10.29 controllera"
        - "192.168.10.30 hosta1"
        - "192.168.10.31 hosta2"
        - "192.168.10.32 hosta3"
        - "192.168.10.34 hosta4"
        - "192.168.10.35 hostac1"
        - "192.168.10.36 hostac2"
        - "192.168.10.37 hostac3"
