---

#updating the ubntu and centOS 
- hosts: all
  become: true
  tasks:
   - name: install updates (CentOS)
     dnf:
       update_only : yes
       use_backend: dnf4
       update_cache : yes
     when: ansible_distribution == "CentOS"

- hosts: all
  become: true
  tasks:
   - name: install updates (Ubuntu)
     apt:
       upgrade : dist
       update_cache : yes
     when: ansible_distribution == "Ubuntu"

# ubuntu 
- hosts: web_servers
  become: true
  tasks:
   - name: install multiple packages
     apt:
       name: 
         - apache2
         - libapache2-mod-php

       state: latest 
     when: ansible_distribution == "Ubuntu"
     
#centOS
   - name: install httpd package on CentOS 
     dnf:
       name:
         - httpd
         - php

       state: latest 
       use_backend: dnf4
     when: ansible_distribution == "CentOS"