---

- hosts: all
  become: true
  tasks:
#ubuntu
   - name: install multiple packages
     apt:
       name: 
         - apache2
         - libapache2-mod-php

       state: latest 
       update_cache : yes
     when: ansible_distribution == "Ubuntu"
     
#centOS 
- hosts: centos
  become: true
  tasks:
   - name: install httpd package
     dnf:
       name:
         - httpd
         - php

       state: latest 
       use_backend: dnf4
       update_cache : yes
     when: ansible_distribution == "CentOS"

  

    

    
