---
- hosts: host1,host2,host3
  become: yes
  tasks:
    - name: Set static IP address
      ansible.builtin.file:
        path: /etc/netplan/01-netcfg.yaml
        state: present
        content: |
          network:
            version: 2
            renderer: networkd
            ethernets:
              enp0s3:
                addresses:
                  - 192.168.1.11/24
                gateway4: 192.168.1.1
                nameservers:
                  search: [example.com]
                  addresses: [8.8.8.8, 8.8.4.4]

    - name: Apply network changes
      ansible.builtin.command: netplan apply
