---
- name: Configure Ubuntu server for web hosting
  hosts: ldd
  become: yes
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Upgrade all packages on servers
      apt:
        upgrade: dist
        force_apt_get: yes

    - name: Install Apache web server
      apt:
        name: apache2
        state: present

    - name: Install PostgreSQL and libpq-dev
      apt:
        name:
          - postgresql
          - python3-psycopg2
          - libpq-dev
        state: present

    - name: Install Python 3 and pip
      apt:
        name: python3-pip
        state: present

    - name: Install Django
      pip:
        name: Django
        executable: pip3

    - name: Install psycopg2-binary
      pip:
        name: psycopg2-binary
        executable: pip3

    - name: Copy requirements.txt from local machine to target host
      copy:
        src: /home/ka/ansible_tutorial/requirements.txt  # Local path
        dest: /home/ka/requirements.txt                   # Target host path
      become: yes

    - name: Install Python requirements from requirements.txt
      pip:
        requirements: /home/ka/requirements.txt
        executable: pip3

    # Configure Apache2 to host the Django application
    - name: Create a virtual host configuration file for Django
      template:
        src: django.conf.j2  # Template file for Apache2 virtual host
        dest: /etc/apache2/sites-available/django.conf
      become: yes

    - name: Enable the Django virtual host
      command: a2ensite django.conf
      become: yes
      notify:
        - Restart Apache

    - name: Disable the default Apache2 site
      command: a2dissite 000-default
      become: yes
      notify:
        - Restart Apache

    # ... rest of your playbook ...

    - name: Start Apache2 service
      service:
        name: apache2
        state: started
      notify:
        - Restart Apache

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted