---

# ping the host from controler . Install python3 and dnf through adhoc commands . ansible all -m apt -a "name=python3 state=latest" --become --ask-become-pass, ansible all -m apt -a "name=dnf state=latest" --become --ask-become-pass .

- name: Setup Environment
  hosts: base
  remote_user: ka
  become: yes

#set the python path to use ansible latest version
 - name: Ensure Python 3 is installed
  become: yes
  become_method: sudo
  command: /usr/bin/python3 --version
  ignore_errors: yes
  register: python_check

- name: Install Python 3 if not already installed
  become: yes
  become_method: sudo
  apt:
    name: python3
    state: present
  when: "python_check.rc != 0"

- name: Set Python 3 as the default interpreter for Ansible
  become: yes
  become_method: sudo
  alternatives:
    name: python
    path: /usr/bin/python3


# #install the requied packages 
#     - name: Install dnf
#       package:
#         name: dnf
#         state: present

# Set the hosts entry on the target hosts 
- name: Update Hosts File
  hosts: new
  remote_user: ka
  become: yes
  tasks:
    - name: Add host entries to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items:
        - "192.168.10.29 controllera"
        - "192.168.10.30 hosta1"
        - "192.168.10.31 hosta2"
        - "192.168.10.32 hosta3"
        - "192.168.10.34 hosta4"
        - "192.168.10.35 hostac1"
        - "192.168.10.36 hostac2"
        - "192.168.10.38 hostac3"

 # Rmeove the hosts Entry 
# - name: Remove Host Entries from /etc/hosts
#   hosts: new
#   remote_user: ka
#   become: yes
#   tasks:
#     - name: Remove host entries from /etc/hosts
#       lineinfile:
#         path: /etc/hosts
#         state: absent
#         regexp: "^{{ item }}"
#       with_items:
#         - "192.168.10.30 hosta1"
#         - "192.168.10.31 hosta2"
#         - "192.168.10.32 hosta3"

