# Harden the system and update teh host entry to hosts with Master ipaddress 
# command : ansible-playbook -i inventory/hosts Ubuntu_hardening.yml -K

---
- hosts: all
  become: true
  tasks:
    - name: Update system software
      apt:
        update_cache: yes
        upgrade: dist
# installing teh ufw firewall
    - name: Install UFW (Uncomplicated Firewall)
      apt:
        name: ufw
        state: present
      become: yes
      tags: [firewall]
# configuring the ufw 
    - name: Configure UFW
      ufw:
        state: enabled
        policy: deny
      become: yes
      tags: [firewall]
# ufw allow 22 port ( more security we use custom port)
    - name: Allow SSH through UFW on port 22
      ufw:
        rule: allow
        port: 22
      become: yes
      tags: [firewall]
# ssh through root user managment 
    - name: Disable root login via SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
      become: yes
      notify: Restart SSH

    - name: Change SSH port to 22
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^Port'
        line: 'Port 22'
      become: yes
      notify: Restart SSH

    - name: Disable password-based SSH authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'
      become: yes
      notify: Restart SSH
# installing the auth security tool
    - name: Install and configure Fail2ban
      apt:
        name: fail2ban
        state: present
      become: yes
      notify: Restart Fail2ban

    - name: Enable automatic security updates
      apt:
        name: unattended-upgrades
        state: present
      become: yes
      notify: Configure Unattended-Upgrades
    - name: Configure core dumps
      command: >
        echo "* hard core 0" > /etc/security/limits.conf
      become: yes
#disablethe root user a nologin 
    - name: Set root user to nologin
      user:
        name: root
        shell: /usr/sbin/nologin
      become: yes

  handlers:
    - name: Restart SSH
      service:
        name: ssh
        state: restarted

    - name: Restart Fail2ban
      service:
        name: fail2ban
        state: restarted
# allow upgrades 
    - name: Configure Unattended-Upgrades
      command: dpkg-reconfigure --priority=low unattended-upgrades
      become: yes
# update host entries ( master node is enough )
    - name: Add host entries to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items:
        - "172.17.2.128    master"
        - "172.17.2.129    host1"
        - "172.17.2.130    host2"
        - "172.17.2.131    host3"
        - "172.17.2.132    host4"
        - "172.17.2.133    host5"
        - "172.17.2.134    host6"
        - "172.17.2.135    host7"

  tags: [ubuntu_hardening]
